# Generated by Django 3.2.19 on 2023-06-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('IDtype', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=200)),
                ('Detail', models.CharField(max_length=500)),
                ('Image1', models.CharField(max_length=200)),
                ('Image2', models.CharField(max_length=200)),
                ('Linkdownload', models.CharField(max_length=500)),
            ],
        ),
    ]
