# Generated by Django 3.2.19 on 2023-06-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Linkdownload',
            field=models.FileField(default=None, upload_to='file/'),
        ),
    ]
