# Generated by Django 3.2.19 on 2023-06-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230607_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='Image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
