# Generated by Django 3.2.19 on 2023-06-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_collection_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
