# Generated by Django 3.2.19 on 2023-06-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_custumer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custumer',
        ),
    ]
