# Generated by Django 3.2.19 on 2023-06-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_download'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='collection_id',
            new_name='collection',
        ),
    ]
